worker_processes 1;

events {
  worker_connections 1024;
}

http {
  upstream origin {
    server origin-1;
  }

  upstream backend {
    server backend-1;
  }

  server {
    listen 80 default_server;
    server_name _;

    location /origin {
      proxy_pass http://origin;

      proxy_intercept_errors on;
      error_page 404 = @backend;
    }

    location @backend {
      proxy_pass http://backend;
    }
  }
}
