worker_processes 1;

events {
  worker_connections 1024;
}

http {
  server {
    listen 80 default_server;
    server_name _;

    location /origin/existing-resource {
      return 200 "hello from origin";
    }

    location /origin/nonexistent-resource {
      return 404 "not found in origin";
    }
  }
}
