worker_processes 1;

events {
  worker_connections 1024;
}

http {
  upstream origin {
    server origin;
  }

  server {
    listen 80 default_server;
    server_name _;

    location /origin {
      internal;

      rewrite /origin/hls/(.*)$ /$1 break;
      proxy_pass http://origin;
    }

    location /hls {
      vod hls;
      vod_mode remote;
      vod_upstream_location /origin;
    }
  }
}
