worker_processes 1;

events {
  worker_connections 1024;
}

http {
  upstream origin {
    server origin;
  }

  server {
    listen 80 default_server;
    server_name _;

    location / {
      akamai_token_validate $arg_token;
      akamai_token_validate_key d00d;

      proxy_pass http://origin;
    }
  }
}
