worker_processes 1;

events {
  worker_connections 1024;
}

http {
  include mime.types;

  access_log /dev/null;
  error_log /dev/null;

  accounting on;
  accounting_interval 10;
  accounting_log /var/log/nginx/access.log notice;

  server {
    listen 80 default_server;
    server_name  _;

    location /default {
      return 200;
    }

    location /test-0 {
      accounting_id "test.com[0]";
      return 200;
    }

    location /test-1 {
      accounting_id "test.com[0,1]";
      return 200;
    }

    location /test-2 {
      accounting_id "test.com[1,2]";
      return 200;
    }

    location /test-3 {
      accounting_id "test.com";
      return 200;
    }

    location /test-4 {
      accounting_id "test.com[]";
      return 200;
    }

    location /test-5 {
      accounting_id "test.com[,,b]";
      return 200;
    }

    location /test-6 {
      accounting_id "test.com[ 0,,b]";
      return 200;
    }

    location /test-7 {
      accounting_id "test.com[,,b10]";
      return 200;
    }
  }
}
