worker_processes 2;

events {
  worker_connections 1024;
}

http {
  geoip2 /usr/share/GeoIP/GeoLite2-Country.mmdb {
    $geoip2_data_country_code default=UK source=$remote_addr country iso_code;
  }

  map $geoip2_data_country_code $country_allowed_for_vhost {
    default true;
    RU false;
    BY false;
  }

  server {
    listen 80 default_server;
    server_name _;

    if ($country_allowed_for_vhost != true) {
      return 403;
    }

    real_ip_header X-Forwarded-For;
    set_real_ip_from 0.0.0.0/0;

    location /test {
      return 200;
    }
  }
}
