worker_processes 1;

events {
  worker_connections 1024;
}

http {
  server {
    listen 80 default_server;
    server_name _;

    root /media;

    location /non-adaptive {
      rewrite ^/non-adaptive/(.*)$ /$1 break;
    }

    location /adaptive {
      rewrite ^/adaptive/(.*)$ /$1 break;
    }
  }
}
