worker_processes 1;

events {
  worker_connections 1024;
}

http {
  upstream storage_origin {
    server storage-origin-4;
  }

  server {
    listen 80 default_server;
    server_name _;

    location / {
      proxy_pass http://storage_origin;
    }
  }
}

# Если запрос к `video__720p.mp4` вернул 404, нужно преобразовать
# его к `video__480p.mp4`
