worker_processes 1;

events {
  worker_connections 1024;
}

http {
  upstream origin {
    server origin-4;
  }

  upstream backend {
    server backend-4;
  }

  upstream storage {
    server storage-4;
  }

  server {
    listen 80 default_server;
    server_name _;

    # `non-adaptive` - для этого ресурса не включена функция адаптивности
    # Запросы перенаправляются в origin как есть

    location /non-adaptive {
      internal;

      rewrite ^/non-adaptive/([^\/]+)/non-adaptive/(.*)$ /non-adaptive/$2 break;
      proxy_pass http://origin;
    }

    location /hls/non-adaptive {
      vod hls;
      vod_mode remote;
      vod_upstream_location /non-adaptive;
    }

    # `adaptive` - для этого ресурса функция адаптивности включена
    # Запросы преобразуются к multi-source и направляются в storage
    # Если storage возвращает ошибку, запрос перенаправляется в backend
    # Backend возвращает страницу с информацией о ходе рескейлинга

    location /adaptive {
      internal;

      rewrite ^/adaptive/([^\/]+)/adaptive/(.*)$ /adaptive/$2 break;
      proxy_pass http://storage;
    }

    location /hls/adaptive {
      # Значения выходных разрешений передаются в шаблон из параметров ресурса
      rewrite ^/hls/adaptive(.*)\.mp4\/master\.m3u8
              /hls/adaptive$1__,240,360,480,720,p.mp4.urlset/master.m3u8;

      vod hls;
      vod_mode remote;
      vod_upstream_location /adaptive;

      proxy_intercept_errors on;
      error_page 404 502 = @backend;
    }

    location @backend {
      # URL источника и выходные параметры передаются в параметрах origin и out
      rewrite ^/hls/adaptive/(.*)__,240,360,480,720,p\.mp4\.urlset\/master\.m3u8$
              /rescale?origin=http://origin-4/adaptive/$1.mp4&out=240&out=360&out=480&out=720
              break;
      proxy_set_header "Authorization" "secret";

      proxy_pass http://backend;
    }
  }
}
